export const audioCardData = [
  {
    key: "au0",
    title: "Elder Caius",
    subtitle: "Kailash, When It Rises (Single)",
    stack: "*",
    image: [],
    link: "https://eldercaius.bandcamp.com/album/kailash-when-it-rises",
  },
  {
    key: "au0",
    title: "Evan Watton",
    subtitle: "RPM 2021 (Album)",
    stack: "*",
    image: [],
    link: "https://evnwttn.bandcamp.com/album/rpm-2021",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Kintsukuroi (EP)",
    stack: "Vocal Performance & Recording, Co-Producer, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/album/kintsukuroi",
  },
  {
    key: "au0",
    title: "Evan Watton",
    subtitle: "västra (Demo Compilation)",
    stack: "*",
    image: [],
    link: "https://soundcloud.com/evnwttn01/sets/vaestra",
  },
  {
    key: "au0",
    title: "Evan Watton",
    subtitle: "mnchrmtc (Demo Compilation)",
    stack: "*",
    image: [],
    link: "https://soundcloud.com/evnwttn01/sets/mnchrmtc",
  },
  {
    key: "au0",
    title: "Caius Cosades",
    subtitle: "Barrows / Drone of Flies (EP)",
    stack: "*",
    image: [],
    link: "https://caiuscosades.bandcamp.com/album/barrows-drone-of-flies",
  },
  {
    key: "au0",
    title: "Caius Cosades",
    subtitle: "Monochromatic (Single)",
    stack: "*",
    image: [],
    link: "https://caiuscosades.bandcamp.com/track/monochromatic",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Ivory (Single)",
    stack: "Vocal Performance, Co-Producer, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/track/ivory",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Gideon (Single)",
    stack: "Vocal Performance, Co-Producer, Mixing, Mastering, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/track/gideon",
  },
  {
    key: "au0",
    title: "The Northern",
    subtitle: "Imperium (EP)",
    stack: "Sampling on 'Imperium', Bass (Credited)",
    image: [],
    link: "https://thenortherncanada.bandcamp.com/album/imperium",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Gideon (Single)",
    stack: "Vocal Performance, Co-Producer, Mixing, Mastering, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/track/gideon",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Ocean of Colour (EP)",
    stack: "Vocal Performance, Co-Producer, Bass Recording, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/album/ocean-of-colour",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Shatter (Single)",
    stack: "Vocal Performance, Co-Producer, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/track/shatter",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Torchbearer (Single)",
    stack: "Vocal Performance, Co-Producer, Mixing, Mastering, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/track/torchbearer",
  },
  {
    key: "au0",
    title: "Ascariasis",
    subtitle: "Against The Tempest (Single)",
    stack: "Vocal Performance, Co-Producer, Mixing, Mastering, Lyrics",
    image: [],
    link: "https://ascariasis.bandcamp.com/track/against-the-tempest",
  },
];
